# config/yolov8_config.yaml

# Caminho base para os dados (relativo ao diretório onde o script é executado)
path: data/processed  # Diretório base para os dados de treino e validação

# Caminhos relativos para os conjuntos de dados de treino e validação
train: train/images      # Subdiretório relativo para imagens de treino
val: valid/images        # Subdiretório relativo para imagens de validação

# Configurações de classes
nc: 1                    # Número de classes (nuvens)
names: ['cloud']          # Nome da classe
